name: unicorn_robot_flutter_web
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.6.1
  go_router_builder: ^2.7.1
  flutter_gen_runner: ^5.8.0
  flutter_dotenv: ^5.2.1
  build_runner: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml
  assets:
    exclude:
      - .env


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/icons/
    - assets/sounds/
